### ISSUE TITLE
cpm don't support pinto

### ISSUE THREAD

**Issue by JaSei** [skaji/cpm#37]
Hello, we use [pinto](https://metacpan.org/pod/distribution/Pinto/bin/pinto) as our darkpan and cpm don't work with him...

`cpm install -v --mirror "http://pinto.srv.int.avast.com:3111" App::Phoenix::Zorro`

```
25492 FAIL resolve   (0.162sec) App::Phoenix::Zorro
FAIL resolve App::Phoenix::Zorro
0 distribution installed.
```

**Comment by skaji** [comment]
Some questions.
I suspect pinto uses 02packages.details.txt for indexing modules, so that it can index only 1 specific version of a module at the same time (that is, it cannot index both Foo v1.0.0 and Foo v1.1.0 at the same time).
* Are you satisfied with 02packages.details.txt?
* Are you happy if pinto indexes multiple versions of modules, and cpm have a flexible resolver enough to handle such index?

**Comment by tynovsky** [comment]
It also seems to me that 02packages.details.txt only stores one specific version, I think your suspecting is correct. It doesn't limit us at the moment. Is there any other darkpan which indexes multiple versions?

**Comment by TiMBuS** [comment]
@skaji Pinto (and Minicpan, OrePAN, etc) will likely never index multiple versions of packages. Your best plan is to provide a --mirror-only option, and then fetch everything from the index regardless of version (unless there is a snapshot)

@tynovsky sadly, all cpan indexers only list the latest dist version. You need to setup a metacpan or cpanmetadb to index old dists for you (I have done this at my company).
If any menlo/cpanm application uses your custom meta-index, it will discover the package location eg: `T/TE/TEST/Package-v1.tar.gz` and then it will try to fetch it from each mirror sequentially. 02packages.details.txt is ignored.

However if you do setup a cpanmetadb, cpm still won't work for you as it will -always- use the public cpanmetadb.

See here it is hardcoded:
https://github.com/skaji/cpm/blob/master/lib/App/cpm.pm#L27
Passed to the resolver:
https://github.com/skaji/cpm/blob/master/lib/App/cpm.pm#L160
Used here:
https://github.com/skaji/cpm/blob/master/lib/App/cpm/Worker/Resolver/MetaDB.pm#L19

It would be good if cpm took a `--cpanmetadb=my.local.metadb` option

**Comment by TiMBuS** [comment]
I checked out @oalders changes at https://github.com/oalders/cpm/tree/more-cpan-options and added a `--mirror-only option`. I also had to pass through any custom `--mirror`s to Menlo when it was created.
It looked like it would work, but because Cpm turns off Wget and LWP support, Menlo failed because my repository uses SSL and my HTTP::Tinyish apparently doesn't support that.
Either way I think adding those cpanm options is a good step forward to getting this issue fixed.

**Comment by JaSei** [comment]
Will be possible add `-mirror-only` option? Becuase `cpm` is really good (fast)...

**Comment by skaji** [comment]
Please try https://metacpan.org/release/SKAJI/App-cpm-0.200-TRIAL

**Comment by JaSei** [comment]
Work like a charm - thank you.
